/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.digisign.util;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignBand;
import net.sf.jasperreports.engine.design.JRDesignExpression;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JRDesignSection;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.type.HorizontalAlignEnum;
import net.sf.jasperreports.engine.type.ScaleImageEnum;

/**
 *
 * @author newbiecihuy
 */
public class DynamicJasperReport {

    private static JasperDesign getJasperDesign() throws JRException,
            ParseException {

        JRDesignExpression expression = new JRDesignExpression();
        JRDesignBand band = new JRDesignBand();

        // JasperDesign
        JasperDesign jasperDesign = new JasperDesign();
        jasperDesign.setName("ImLoggerDynamicReport");
        jasperDesign.setPageWidth(595);
        jasperDesign.setPageHeight(842);
        jasperDesign.setLeftMargin(20);
        jasperDesign.setRightMargin(20);
        jasperDesign.setTopMargin(20);
        jasperDesign.setBottomMargin(20);
        jasperDesign.setColumnWidth(555);
        jasperDesign.setColumnSpacing(0);

        // Fonts
        jasperDesign.addStyle(DynamicReportUtil.getNormalStyle());

        // Parameters
        jasperDesign.addParameter(DynamicReportUtil.getParameter("ReportTitle",
                java.lang.String.class));
        jasperDesign.addParameter(DynamicReportUtil.getParameter("imagePath",
                java.lang.String.class));
        jasperDesign.addParameter(DynamicReportUtil.getParameter("userId",
                java.lang.String.class));

        // Query
//        JRDesignQuery query = new JRDesignQuery();
//        query.setText("SELECT * FROM imlog");
//        jasperDesign.setQuery(query);

        // Fields
        jasperDesign.addField(DynamicReportUtil.getField("log_id",
                java.lang.Integer.class));
        jasperDesign.addField(DynamicReportUtil.getField("Time",
                java.sql.Timestamp.class));
        jasperDesign.addField(DynamicReportUtil.getField("Category",
                java.lang.String.class));
        jasperDesign.addField(DynamicReportUtil.getField("Severity",
                java.lang.String.class));
        jasperDesign.addField(DynamicReportUtil.getField("Message",
                java.lang.String.class));

        // Title
        band = new JRDesignBand();
        band.setHeight(73);
        band.addElement(DynamicReportUtil.getImage(0, 8, 97, 50,
                ScaleImageEnum.RETAIN_SHAPE, HorizontalAlignEnum.LEFT,
                "imagePath"));
        band.addElement(DynamicReportUtil.getTextField(109, 6, 328, 20,
                HorizontalAlignEnum.CENTER, DynamicReportUtil.getNormalStyle(),
                12, "$P{ReportTitle}", java.lang.String.class));
        band.addElement(DynamicReportUtil.getStaticText(182, 26, 191, 20,
                "Daily Log Report (Teminos T24)",
                DynamicReportUtil.getNormalStyle(), HorizontalAlignEnum.CENTER,
                0));
        band.addElement(DynamicReportUtil.getStaticText(156, 46, 243, 20,
                "(Criteria: Field = “” and Field = “B” and Field = ”C”)",
                DynamicReportUtil.getNormalStyle(), HorizontalAlignEnum.CENTER,
                0));
        band.addElement(DynamicReportUtil.getStaticText(462, 4, 28, 13,
                "Date:", DynamicReportUtil.getNormalStyle(),
                HorizontalAlignEnum.RIGHT, 0));
        band.addElement(DynamicReportUtil.getStaticText(462, 20, 28, 16,
                "Time:", DynamicReportUtil.getNormalStyle(),
                HorizontalAlignEnum.RIGHT, 0));
        band.addElement(DynamicReportUtil.getStaticText(422, 38, 68, 16,
                "Generated By:", DynamicReportUtil.getNormalStyle(),
                HorizontalAlignEnum.RIGHT, 0));
        band.addElement(DynamicReportUtil.getStaticText(496, 4, 50, 13,
                new SimpleDateFormat("dd.MM.yyyy").format(new Date())
                        .toString(), DynamicReportUtil.getNormalStyle(),
                HorizontalAlignEnum.LEFT, 0));
        band.addElement(DynamicReportUtil
                .getStaticText(496, 20, 50, 16, new SimpleDateFormat("h.mm a")
                        .format(new Date()).toString(), DynamicReportUtil
                        .getNormalStyle(), HorizontalAlignEnum.LEFT, 0));
        band.addElement(DynamicReportUtil.getTextField(496, 38, 50, 16,
                HorizontalAlignEnum.LEFT, DynamicReportUtil.getNormalStyle(),
                10, "$P{userId}", java.lang.String.class));
        jasperDesign.setTitle(band);

        // Column header
        band = new JRDesignBand();
        band.setHeight(20);
        band.addElement(DynamicReportUtil
                .getStaticText(0, 0, 63, 20, "Log ID",
                        DynamicReportUtil.getNormalStyle(),
                        HorizontalAlignEnum.LEFT, 1));
        band.addElement(DynamicReportUtil
                .getStaticText(63, 0, 120, 20, "Time",
                        DynamicReportUtil.getNormalStyle(),
                        HorizontalAlignEnum.LEFT, 1));
        band.addElement(DynamicReportUtil.getStaticText(183, 0, 80, 20,
                "Category", DynamicReportUtil.getNormalStyle(),
                HorizontalAlignEnum.LEFT, 1));
        band.addElement(DynamicReportUtil.getStaticText(263, 0, 100, 20,
                "Severity", DynamicReportUtil.getNormalStyle(),
                HorizontalAlignEnum.LEFT, 1));
        band.addElement(DynamicReportUtil.getStaticText(363, 0, 192, 20,
                "Message", DynamicReportUtil.getNormalStyle(),
                HorizontalAlignEnum.LEFT, 1));
        jasperDesign.setColumnHeader(band);

        // Detail
        band = new JRDesignBand();
        band.setHeight(20);
        band.addElement(DynamicReportUtil.getTextField(0, 0, 63, 20,
                HorizontalAlignEnum.LEFT, DynamicReportUtil.getNormalStyle(),
                10, "$F{log_id}", java.lang.Integer.class));
        band.addElement(DynamicReportUtil.getTextField(63, 0, 120, 20,
                HorizontalAlignEnum.LEFT, DynamicReportUtil.getNormalStyle(),
                10, "$F{Time}", java.sql.Timestamp.class));
        band.addElement(DynamicReportUtil.getTextField(183, 0, 80, 20,
                HorizontalAlignEnum.LEFT, DynamicReportUtil.getNormalStyle(),
                10, "$F{Category}", java.lang.String.class));
        band.addElement(DynamicReportUtil.getTextField(263, 0, 100, 20,
                HorizontalAlignEnum.LEFT, DynamicReportUtil.getNormalStyle(),
                10, "$F{Severity}", java.lang.String.class));
        band.addElement(DynamicReportUtil.getTextField(363, 0, 192, 20,
                HorizontalAlignEnum.LEFT, DynamicReportUtil.getNormalStyle(),
                10, "$F{Message}", java.lang.String.class));
        ((JRDesignSection) jasperDesign.getDetailSection()).addBand(band);

        // Column Footer
        band = new JRDesignBand();
        band.setHeight(59);
        band.addElement(DynamicReportUtil.getTextField(227, 17, 100, 20,
                HorizontalAlignEnum.CENTER, DynamicReportUtil.getNormalStyle(),
                10, "$V{PAGE_NUMBER}", java.lang.String.class));
        jasperDesign.setColumnFooter(band);

        // Page Footer
        band = new JRDesignBand();
        jasperDesign.setPageFooter(band);

        // Summary
        band = new JRDesignBand();
        band.setHeight(31);
        band.addElement(DynamicReportUtil.getStaticText(207, 5, 141, 20,
                "---- End of the report ----",
                DynamicReportUtil.getNormalStyle(), HorizontalAlignEnum.CENTER,
                0));
        jasperDesign.setSummary(band);

        return jasperDesign;
    }

    public static void main(String[] args) throws Exception {
        Map parameters = new HashMap();
        parameters.put("ReportTitle", "ABCD Company");
         parameters.put("imagePath",
                "C:\\Users\\field\\NetBeansProjects\\PDFReportProject\\src\\main\\webapp\\report\\green_forest.jpg");
//         parameters.put("userId", "");
//        parameters.put("imagePath",
//                "C:\\Users\\Anand\\Pictures\\2013-06\\green_forest.jpg");
        parameters.put("userId", "1234");

        JasperReport jasperReport = JasperCompileManager
                .compileReport(getJasperDesign());
//        Connection conn = DriverManager.getConnection(
//                "jdbc:mysql://localhost:3306/test", "root", "password");
//        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,
//                parameters, conn);
        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,
                parameters);
        JasperExportManager.exportReportToPdfFile(jasperPrint,
                "C://Users//field//NetBeansProjects//PDFReportProject//src//main//webapp//report//test_jasper.pdf");
    }

}
